### ISSUE TITLE
Empty links throw A Name cannot be undefined

### ISSUE THREAD

**Issue by garotosopa** [rkusa/pdfjs#260]
PDF files with "empty links" fail with an exception when used as external documents, although they are valid when viewed in PDF viewers.

The problem seems to be related to the lexer while parsing this snippet from the PDF source:

```
/Dest />>
```

Such file can be created by Chrome with the HTML `<a href="#">A link to nowhere</a>` printed as PDF. Here's a sample file:

[sample.pdf](https://github.com/rkusa/pdfjs/files/6756277/sample.pdf)

And here's the code that triggers the exception:

**main.mjs**

```js
import { createWriteStream, readFileSync } from "fs";
import { Document, ExternalDocument } from "pdfjs";

const buffer = readFileSync("sample.pdf");

const doc = new Document();
const ext = new ExternalDocument(buffer);
doc.addPagesOf(ext);

const writer = createWriteStream("output.pdf");
doc.pipe(writer);
doc.end();
```

```console
$ node main.mjs
(node:118968) UnhandledPromiseRejectionWarning: Error: A Name cannot be undefined
    at new PDFName (/tmp/tmp.LSxyVzZPkP/node_modules/pdfjs/lib/object/name.js:6:13)
    at Function.parse (/tmp/tmp.LSxyVzZPkP/node_modules/pdfjs/lib/object/name.js:105:12)
    at Object.exports.parse (/tmp/tmp.LSxyVzZPkP/node_modules/pdfjs/lib/object/value.js:20:30)
    at Function.parse (/tmp/tmp.LSxyVzZPkP/node_modules/pdfjs/lib/object/dictionary.js:74:30)
    at Object.exports.parse (/tmp/tmp.LSxyVzZPkP/node_modules/pdfjs/lib/object/value.js:20:30)
    at Function.parseInner (/tmp/tmp.LSxyVzZPkP/node_modules/pdfjs/lib/object/object.js:80:28)
    at Function.parse (/tmp/tmp.LSxyVzZPkP/node_modules/pdfjs/lib/object/object.js:68:27)
    at parseObject (/tmp/tmp.LSxyVzZPkP/node_modules/pdfjs/lib/object/reference.js:128:22)
    at PDFReference.get [as object] (/tmp/tmp.LSxyVzZPkP/node_modules/pdfjs/lib/object/reference.js:15:17)
    at Function.addObjectsRecursive (/tmp/tmp.LSxyVzZPkP/node_modules/pdfjs/lib/parser/parser.js:68:35)
```

Is this something that the library should be resilient to?

Thank you in advance and please let me know if there's something I could help with.

**Comment by knash94** [comment]
@garotosopa My hero, I've been having the same issue but didn't manage to pin it down to the anchor tags. Thanks so much for reporting this and saving me days worth of headaches!

Can confirm that changing the anchor tags from `href="#"` to a full url for example `href="https://google.com"` has fixed the issue for me.

**Comment by rkusa** [comment]
@garotosopa Thanks a lot for the  report and especially the research of the cause you've already put into it! I've added your sample PDF to the repo to use it for a test, I hope this is ok for you. I'll release a new version with the fix alter today 👍

**Comment by garotosopa** [comment]
> @garotosopa Thanks a lot for the report and especially the research of the cause you've already put into it! I've added your sample PDF to the repo to use it for a test, I hope this is ok for you. I'll release a new version with the fix alter today +1

I'm glad the sample file was useful. Thank you for looking into it.

**Comment by wildhart** [comment]
I also got this error which was fixed by updating the package, thanks for your fix!

Before updating though, I tried to catch the error but it was impossible.  Why does this error cause an `UnhandledPromiseRejectionWarning` which cannot be caught by external code?  Is that something you could fix as well?  I need to be confident that errors caused by weird bugs in future pdfs can be reported properly to my users.
