### ISSUE TITLE
Problem using certain PDFs as images

### ISSUE THREAD

**Issue by adittes** [rkusa/pdfjs#57]
First of all, I want to say thanks for creating pdfjs, it really looks like a great library! However, I've run into an issue adding some PDFs as an image:

```
/home/andrew/src/myproj/node_modules/pdfjs/lib/pdf/parser/lexer.js:119
  throw new Error(err)
  ^

Error: EOL expected but not found
    at Lexer._error (/home/andrew/src/myproj/node_modules/pdfjs/lib/pdf/parser/lexer.js:119:9)
    at Lexer.skipEOL (/home/andrew/src/myproj/node_modules/pdfjs/lib/pdf/parser/lexer.js:47:12)
    at Function.PDFXref.parse (/home/andrew/src/myproj/node_modules/pdfjs/lib/pdf/object/xref.js:71:11)
    at Document.parse (/home/andrew/src/myproj/node_modules/pdfjs/lib/pdf/parser/document.js:39:26)
    at parsePDFInfo (/home/andrew/src/myproj/node_modules/pdfjs/lib/image.js:91:10)
    at new module.exports (/home/andrew/src/myproj/node_modules/pdfjs/lib/image.js:30:19)
    at Object.exports.createImage (/home/andrew/src/myproj/node_modules/pdfjs/lib/index.js:16:10)
    at Object.<anonymous> (/home/andrew/src/myproj/testpdf.js:7:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```
This happens with 1.0.0-alpha.1 and 1.0.0-alpha.5.

Here is the test code I am using (running on Linux/Node 4.4.7):

```js
var pdfjs = require('pdfjs');
var fs = require('fs');

var file = '/tmp/my.pdf';

var buf = fs.readFileSync(file);
var img = pdfjs.createImage(buf); // dies here

//var doc = pdfjs.createDocument({});
//doc.image(img);

//var pdf = doc.render();

//fs.writeFileSync('/tmp/new.pdf', pdf.toString(), 'binary');
```

Most PDFs are able to be added (and rendered) with this code, but PDFs from gpo.gov all seem to fail. [Here](https://www.gpo.gov/fdsys/pkg/FR-2016-06-30/pdf/2016-15653.pdf) is an example of such a PDF.

**Comment by rkusa** [comment]
Hi, thanks for reporting. I've updated the PDF parser to work with itext2 generated pdfs (gpo.gov pdfs seems to be created with itext2). Should work with the master branch now?

**Comment by rkusa** [comment]
Feel free to reopen the issue if it does still not work
