### ISSUE TITLE
Error when using a cell with colspan > 1 (upgrading to 2.0)

### ISSUE THREAD

**Issue by knownasilya** [rkusa/pdfjs#99]
I have the following code:

```js
secondHeaderRightRow.cell({
    colspan: 2
}).text(disclaimer, { fontSize: 7 });
```

And get this error:

> stack:"TypeError: Cannot read property 'splice' of null\n    at Row.cell (/Users/iradchenko/workspace/mapgeo/node_modules/pdfjs/lib/row.js:277:34)\n    at createHeader (/Users/iradchenko/workspace/mapgeo/server/api/utils/abutters-report-pdf.js:128:55)\n    at /Users/iradchenko/workspace/mapgeo/server/api/utils/abutters-report-pdf.js:36:5\n    at tryCatcher (/Users/iradchenko/workspace/mapgeo/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/Users/iradchenko/workspace/mapgeo/node_modules/bluebird/js/release/promise.js:512:31)\n    at Promise._settlePromise (/Users/iradchenko/workspace/mapgeo/node_modules/bluebird/js/release/promise.js:569:18)\n    at Promise._settlePromiseCtx (/Users/iradchenko/workspace/mapgeo/node_modules/bluebird/js/release/promise.js:606:10)\n    at Async._drainQueue (/Users/iradchenko/workspace/mapgeo/node_modules/bluebird/js/release/async.js:138:12)\n    at Async._drainQueues (/Users/iradchenko/workspace/mapgeo/node_modules/bluebird/js/release/async.js:143:10)\n...

**Comment by knownasilya** [comment]
Just this code:

```js
secondHeaderRightRow.cell({
    colspan: 2
})
```

creates the same error. If I add an empty string, I get the same error:

```js
secondHeaderRightRow.cell('', {
    colspan: 2
})
```
